export const RPS_ARENA_ADDRESS =
  "0xF43975e3Ab28EDA51699479e04Bd924e5e414713" as const;

// Minimal ABI for interacting with the RPSArena contract from the app.
// Includes the functions and events needed for reading match state and
// sending gameplay transactions.
export const RPS_ARENA_ABI = [
  { inputs: [], name: "AlreadyInQueue", type: "error" },
  { inputs: [], name: "CommitAlreadySubmitted", type: "error" },
  { inputs: [], name: "CommitMissing", type: "error" },
  { inputs: [], name: "DeadlineNotPassed", type: "error" },
  { inputs: [], name: "InvalidCommit", type: "error" },
  { inputs: [], name: "InvalidMatch", type: "error" },
  { inputs: [], name: "InvalidRound", type: "error" },
  { inputs: [], name: "InvalidWager", type: "error" },
  { inputs: [], name: "MatchAlreadyFinished", type: "error" },
  { inputs: [], name: "NoTimeoutToClaim", type: "error" },
  { inputs: [], name: "NotInQueue", type: "error" },
  { inputs: [], name: "NotPlayer", type: "error" },
  { inputs: [], name: "RevealAlreadySubmitted", type: "error" },
  { inputs: [], name: "RevealTooEarly", type: "error" },
  { inputs: [], name: "TransferFailed", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "matchId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "player1",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "player2",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "wager",
        type: "uint256",
      },
    ],
    name: "MatchCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "matchId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "winner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "payoutPlayer1",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "payoutPlayer2",
        type: "uint256",
      },
    ],
    name: "MatchFinished",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "player",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "wager",
        type: "uint256",
      },
    ],
    name: "QueueCancelled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "matchId",
        type: "uint256",
      },
      { indexed: true, internalType: "uint8", name: "round", type: "uint8" },
      {
        indexed: true,
        internalType: "address",
        name: "player",
        type: "address",
      },
    ],
    name: "RoundCommitted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "matchId",
        type: "uint256",
      },
      { indexed: true, internalType: "uint8", name: "round", type: "uint8" },
      { indexed: false, internalType: "int8", name: "result", type: "int8" },
    ],
    name: "RoundResult",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "matchId",
        type: "uint256",
      },
      { indexed: true, internalType: "uint8", name: "round", type: "uint8" },
      {
        indexed: true,
        internalType: "address",
        name: "player",
        type: "address",
      },
      {
        indexed: false,
        internalType: "enum RPSArena.Move",
        name: "move",
        type: "uint8",
      },
    ],
    name: "RoundRevealed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "matchId",
        type: "uint256",
      },
      { indexed: true, internalType: "uint8", name: "round", type: "uint8" },
      {
        indexed: true,
        internalType: "address",
        name: "winner",
        type: "address",
      },
      { indexed: false, internalType: "string", name: "phase", type: "string" },
    ],
    name: "RoundTimeout",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "player",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "wager",
        type: "uint256",
      },
    ],
    name: "WaitingInQueue",
    type: "event",
  },
  { stateMutability: "payable", type: "fallback" },
  {
    inputs: [],
    name: "MAX_ROUNDS",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PHASE_TIMEOUT",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "WINS_TO_FINISH",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "wager", type: "uint256" }],
    name: "cancelEnqueue",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "matchId", type: "uint256" },
      { internalType: "uint8", name: "round", type: "uint8" },
    ],
    name: "claimCommitTimeout",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "matchId", type: "uint256" },
      { internalType: "uint8", name: "round", type: "uint8" },
    ],
    name: "claimRevealTimeout",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "matchId", type: "uint256" },
      { internalType: "uint8", name: "round", type: "uint8" },
      { internalType: "bytes32", name: "commitHash", type: "bytes32" },
    ],
    name: "commitMove",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "wager", type: "uint256" }],
    name: "enqueue",
    outputs: [{ internalType: "uint256", name: "matchId", type: "uint256" }],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "matchId", type: "uint256" }],
    name: "getMatch",
    outputs: [
      { internalType: "address", name: "player1", type: "address" },
      { internalType: "address", name: "player2", type: "address" },
      { internalType: "uint256", name: "wager", type: "uint256" },
      { internalType: "uint8", name: "roundsPlayed", type: "uint8" },
      { internalType: "uint8", name: "wins1", type: "uint8" },
      { internalType: "uint8", name: "wins2", type: "uint8" },
      {
        internalType: "enum RPSArena.MatchStatus",
        name: "status",
        type: "uint8",
      },
      { internalType: "bool", name: "settled", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "matches",
    outputs: [
      { internalType: "address", name: "player1", type: "address" },
      { internalType: "address", name: "player2", type: "address" },
      { internalType: "uint96", name: "wager", type: "uint96" },
      { internalType: "uint8", name: "roundsPlayed", type: "uint8" },
      { internalType: "uint8", name: "wins1", type: "uint8" },
      { internalType: "uint8", name: "wins2", type: "uint8" },
      {
        internalType: "enum RPSArena.MatchStatus",
        name: "status",
        type: "uint8",
      },
      { internalType: "bool", name: "settled", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "nextMatchId",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "matchId", type: "uint256" },
      { internalType: "uint8", name: "round", type: "uint8" },
      { internalType: "enum RPSArena.Move", name: "move", type: "uint8" },
      { internalType: "bytes32", name: "salt", type: "bytes32" },
    ],
    name: "revealMove",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint8", name: "", type: "uint8" },
    ],
    name: "rounds",
    outputs: [
      { internalType: "bytes32", name: "commit1", type: "bytes32" },
      { internalType: "bytes32", name: "commit2", type: "bytes32" },
      { internalType: "enum RPSArena.Move", name: "move1", type: "uint8" },
      { internalType: "enum RPSArena.Move", name: "move2", type: "uint8" },
      { internalType: "uint64", name: "commitDeadline", type: "uint64" },
      { internalType: "uint64", name: "revealDeadline", type: "uint64" },
      { internalType: "bool", name: "revealed1", type: "bool" },
      { internalType: "bool", name: "revealed2", type: "bool" },
      { internalType: "bool", name: "decided", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "waitingPlayer",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  { stateMutability: "payable", type: "receive" },
] as const;
